// ─── CHALLENGE ARENA DATA ───
export const mockChallenges = [
    {
        id: "ch1",
        title: "Crack the Weak Password",
        category: "Password Cracking",
        description: "Use a dictionary attack technique to crack a 4-character password. The hash is: 5f4dcc3b5aa765d61d8327deb882cf99",
        difficulty: "Easy",
        points: 50,
        solved: false,
        hint: "Think of the most common password in the world.",
        answer: "password",
    },
    {
        id: "ch2",
        title: "Identify the Phishing Email",
        category: "Network Security",
        description: "Analyze the email headers and body below. Find the 3 red flags that indicate this is a phishing attempt.",
        difficulty: "Medium",
        points: 100,
        solved: false,
        hint: "Check the sender domain, urgency language, and the link URL mismatch.",
        answer: "domain,urgency,link",
    },
    {
        id: "ch3",
        title: "Find the SQL Injection",
        category: "Beginner Hacking",
        description: "Review the following login form code snippet and identify where the SQL injection vulnerability exists. Input the vulnerable parameter name.",
        difficulty: "Easy",
        points: 75,
        solved: false,
        hint: "Look for unsanitized user input concatenated into a query.",
        answer: "username",
    },
    {
        id: "ch4",
        title: "Decode the Base64 Flag",
        category: "Beginner Hacking",
        description: "A secret message has been encoded: Q3liZXJTZW50aW5leA==. Decode it to capture the flag.",
        difficulty: "Easy",
        points: 25,
        solved: false,
        hint: "This is a Base64 encoded string.",
        answer: "CyberSentinex",
    },
    {
        id: "ch5",
        title: "Buffer Overflow Basics",
        category: "Password Cracking",
        description: "Analyze the C code with a vulnerable strcpy() call. Determine the exact buffer size needed to overwrite the return address.",
        difficulty: "Hard",
        points: 200,
        solved: false,
        hint: "The buffer is 64 bytes, and the saved EBP is 4 bytes before the return address.",
        answer: "72",
    },
    {
        id: "ch6",
        title: "XSS Detection Lab",
        category: "Network Security",
        description: "Find the Cross-Site Scripting vulnerability in the provided search feature. Submit the payload that triggers an alert.",
        difficulty: "Medium",
        points: 150,
        solved: false,
        hint: "Try injecting a script tag in the search parameter.",
        answer: "<script>alert(1)</script>",
    },
    {
        id: "ch7",
        title: "Caesar Cipher Challenge",
        category: "Beginner Hacking",
        description: "Decrypt this message encrypted with a Caesar cipher (shift unknown): 'Khoor Zruog'. Find the original message.",
        difficulty: "Easy",
        points: 50,
        solved: false,
        hint: "Try shifting each letter back by 3 positions.",
        answer: "Hello World",
    },
    {
        id: "ch8",
        title: "Network Packet Analysis",
        category: "Network Security",
        description: "A suspicious TCP packet has flags SYN+FIN set simultaneously. What type of scan is this indicative of?",
        difficulty: "Hard",
        points: 175,
        solved: false,
        hint: "This is an invalid TCP flag combination used in reconnaissance.",
        answer: "XMAS scan",
    },
];

export const challengeCategories = [
    { id: "all", label: "All Challenges", icon: "🎯" },
    { id: "Beginner Hacking", label: "Beginner Hacking", icon: "🔰" },
    { id: "Password Cracking", label: "Password Cracking", icon: "🔑" },
    { id: "Network Security", label: "Network Security", icon: "🌐" },
];

// ─── RESOURCE LIBRARY DATA ───
export const mockResources = [
    {
        id: "res1",
        title: "TryHackMe — Beginner Path",
        category: "Ethical Hacking",
        description: "Interactive cybersecurity labs with guided learning paths for beginners. Start with the Pre-Security path.",
        link: "https://tryhackme.com",
        difficulty: "Beginner",
        type: "Platform",
    },
    {
        id: "res2",
        title: "HackTheBox Academy",
        category: "Ethical Hacking",
        description: "Structured pentesting courses ranging from basic to advanced exploitation techniques.",
        link: "https://academy.hackthebox.com",
        difficulty: "Intermediate",
        type: "Platform",
    },
    {
        id: "res3",
        title: "Fast.ai — Practical Deep Learning",
        category: "Machine Learning",
        description: "Top-down approach to deep learning. Free course covering CNNs, NLP, and real-world model deployment.",
        link: "https://fast.ai",
        difficulty: "Intermediate",
        type: "Course",
    },
    {
        id: "res4",
        title: "Autopsy — Digital Forensics Tool",
        category: "Digital Forensics",
        description: "Open-source digital forensics platform for analyzing disk images, file systems, and artifacts.",
        link: "https://www.autopsy.com",
        difficulty: "Intermediate",
        type: "Tool",
    },
    {
        id: "res5",
        title: "Wireshark Network Analysis",
        category: "Network Security",
        description: "Learn packet analysis with the world's most popular network protocol analyzer.",
        link: "https://wireshark.org",
        difficulty: "Beginner",
        type: "Tool",
    },
    {
        id: "res6",
        title: "OWASP Web Security Testing Guide",
        category: "Ethical Hacking",
        description: "Comprehensive guide to testing web application security. Covers OWASP Top 10 and beyond.",
        link: "https://owasp.org/www-project-web-security-testing-guide/",
        difficulty: "Advanced",
        type: "Guide",
    },
    {
        id: "res7",
        title: "Kaggle — ML Competitions",
        category: "Machine Learning",
        description: "Practice machine learning through real-world datasets and competitions with community solutions.",
        link: "https://kaggle.com",
        difficulty: "Beginner",
        type: "Platform",
    },
    {
        id: "res8",
        title: "Volatility Framework",
        category: "Digital Forensics",
        description: "Advanced memory forensics framework for analyzing RAM dumps and detecting malware artifacts.",
        link: "https://volatilityfoundation.org",
        difficulty: "Advanced",
        type: "Tool",
    },
    {
        id: "res9",
        title: "OverTheWire Wargames",
        category: "Ethical Hacking",
        description: "Terminal-based security challenges. Start with Bandit for Linux basics, then progress to Natas for web.",
        link: "https://overthewire.org/wargames/",
        difficulty: "Beginner",
        type: "CTF",
    },
    {
        id: "res10",
        title: "Nmap Network Scanner",
        category: "Network Security",
        description: "Essential network discovery and security auditing tool. Learn port scanning, OS detection, and scripting.",
        link: "https://nmap.org",
        difficulty: "Beginner",
        type: "Tool",
    },
    {
        id: "res11",
        title: "Andrew Ng's ML Specialization",
        category: "Machine Learning",
        description: "Stanford's foundational ML course on Coursera. Covers supervised/unsupervised learning and neural networks.",
        link: "https://www.coursera.org/specializations/machine-learning-introduction",
        difficulty: "Beginner",
        type: "Course",
    },
    {
        id: "res12",
        title: "SANS DFIR Resources",
        category: "Digital Forensics",
        description: "Curated collection of forensic tools, cheat sheets, and investigation methodologies from SANS Institute.",
        link: "https://www.sans.org/dfir/",
        difficulty: "Advanced",
        type: "Guide",
    },
];

export const resourceCategories = [
    { id: "all", label: "All Resources", icon: "📚" },
    { id: "Ethical Hacking", label: "Ethical Hacking", icon: "🏴‍☠️" },
    { id: "Machine Learning", label: "Machine Learning", icon: "🧠" },
    { id: "Digital Forensics", label: "Digital Forensics", icon: "🔍" },
    { id: "Network Security", label: "Network Security", icon: "🌐" },
];

// ─── PROJECTS DATA ───
export const mockProjects = [
    {
        id: "proj1",
        name: "NetScanner Pro",
        author: "NeoCypher",
        avatar: "👾",
        description: "Open-source network vulnerability scanner with automated reporting. Supports TCP/UDP scanning and service detection.",
        techStack: ["Python", "Scapy", "React", "FastAPI"],
        githubLink: "https://github.com/example/netscanner",
        likes: 342,
        screenshots: [],
    },
    {
        id: "proj2",
        name: "PhishGuard AI",
        author: "CryptoFox",
        avatar: "🦊",
        description: "Machine learning model that detects phishing emails with 97% accuracy using NLP and URL analysis.",
        techStack: ["Python", "TensorFlow", "Flask", "React"],
        githubLink: "https://github.com/example/phishguard",
        likes: 256,
        screenshots: [],
    },
    {
        id: "proj3",
        name: "CryptoVault",
        author: "Sh4dowByte",
        avatar: "🕵️",
        description: "End-to-end encrypted password manager with zero-knowledge architecture and biometric auth support.",
        techStack: ["Rust", "WebAssembly", "React", "AES-256"],
        githubLink: "https://github.com/example/cryptovault",
        likes: 189,
        screenshots: [],
    },
    {
        id: "proj4",
        name: "MalwareScope",
        author: "V1rusQueen",
        avatar: "🦠",
        description: "Automated malware analysis sandbox with behavioral detection, network traffic monitoring, and YARA rule matching.",
        techStack: ["Python", "Docker", "YARA", "MongoDB"],
        githubLink: "https://github.com/example/malwarescope",
        likes: 421,
        screenshots: [],
    },
    {
        id: "proj5",
        name: "CTF Toolkit",
        author: "ByteStorm",
        avatar: "⚡",
        description: "All-in-one CTF toolkit with integrated decoders, hash crackers, steganography tools, and forensic utilities.",
        techStack: ["Python", "Next.js", "WebSocket"],
        githubLink: "https://github.com/example/ctftoolkit",
        likes: 178,
        screenshots: [],
    },
];

// ─── NEWS FEED ───
export const mockNews = [
    {
        id: "news1",
        title: "Critical Zero-Day Vulnerability Found in Popular VPN Software",
        description: "Security researchers have discovered a remote code execution vulnerability affecting millions of VPN users worldwide.",
        source: "CyberOps Daily",
        link: "#",
        timestamp: "2h ago",
        category: "Vulnerability",
    },
    {
        id: "news2",
        title: "AI-Powered Threat Detection: The Future of SOC Operations",
        description: "New research shows that AI-powered SIEM systems can reduce alert fatigue by 80% in security operations centers.",
        source: "SecurityWeek",
        link: "#",
        timestamp: "5h ago",
        category: "AI",
    },
    {
        id: "news3",
        title: "Largest Data Breach of 2026 Exposes 50M Records",
        description: "A major social media platform confirms a data breach involving usernames, emails, and hashed passwords.",
        source: "DarkReading",
        link: "#",
        timestamp: "1d ago",
        category: "Breach",
    },
    {
        id: "news4",
        title: "New Ransomware Variant Uses AI to Evade Detection",
        description: "Threat actors deploy a ransomware strain that uses machine learning to adapt its signatures and bypass EDR solutions.",
        source: "BleepingComputer",
        link: "#",
        timestamp: "1d ago",
        category: "Malware",
    },
    {
        id: "news5",
        title: "Open Source Tool Automates OWASP Top 10 Testing",
        description: "A new GitHub project provides automated scanning for all OWASP Top 10 vulnerabilities with detailed reporting.",
        source: "Hacker News",
        link: "#",
        timestamp: "2d ago",
        category: "Tool",
    },
];

// ─── POLLS ───
export const mockPolls = [
    {
        id: "poll1",
        question: "Best AI framework for cybersecurity?",
        options: [
            { label: "TensorFlow", votes: 42 },
            { label: "PyTorch", votes: 67 },
            { label: "Scikit-learn", votes: 23 },
            { label: "JAX", votes: 18 },
        ],
        totalVotes: 150,
        author: "NeoCypher",
        avatar: "👾",
        timestamp: "3h ago",
    },
    {
        id: "poll2",
        question: "What's your favorite CTF category?",
        options: [
            { label: "Web Exploitation", votes: 55 },
            { label: "Binary/Pwn", votes: 38 },
            { label: "Cryptography", votes: 29 },
            { label: "Forensics", votes: 34 },
            { label: "OSINT", votes: 22 },
        ],
        totalVotes: 178,
        author: "Sh4dowByte",
        avatar: "🕵️",
        timestamp: "1d ago",
    },
];

// ─── ACHIEVEMENTS ───
export const mockAchievements = [
    { id: "ach1", icon: "📝", title: "First Post", description: "Made your first community feed post", unlocked: true, color: "#39FF14" },
    { id: "ach2", icon: "🏆", title: "First Hackathon", description: "Participated in your first hackathon event", unlocked: true, color: "#ffaa00" },
    { id: "ach3", icon: "👥", title: "Team Builder", description: "Created or joined a team", unlocked: true, color: "#00e676" },
    { id: "ach4", icon: "⭐", title: "Top Contributor", description: "Reached 1000+ reputation points", unlocked: true, color: "#ff6b6b" },
    { id: "ach5", icon: "🎯", title: "Challenge Hunter", description: "Completed 5 arena challenges", unlocked: false, color: "#a78bfa" },
    { id: "ach6", icon: "🔥", title: "7-Day Streak", description: "Logged in for 7 consecutive days", unlocked: false, color: "#f97316" },
    { id: "ach7", icon: "💡", title: "Knowledge Sharer", description: "Shared 10 resources with the community", unlocked: false, color: "#06b6d4" },
    { id: "ach8", icon: "🛡️", title: "Security Expert", description: "Completed all beginner challenges", unlocked: false, color: "#39FF14" },
];

// ─── SKILL MATCHMAKING ───
export const mockMatchProfiles = [
    { id: "m1", name: "Sh4dowByte", avatar: "🕵️", skills: ["Python", "Reverse Engineering", "Binary Exploitation"], matchScore: 92 },
    { id: "m2", name: "CryptoFox", avatar: "🦊", skills: ["AI/ML", "Python", "Prompt Injection"], matchScore: 87 },
    { id: "m3", name: "V1rusQueen", avatar: "🦠", skills: ["Malware Analysis", "C++", "Threat Intel"], matchScore: 78 },
    { id: "m4", name: "ByteStorm", avatar: "⚡", skills: ["Web Security", "JavaScript", "OSINT"], matchScore: 74 },
    { id: "m5", name: "ZeroDayZen", avatar: "🧘", skills: ["Network Security", "Wireshark", "Python"], matchScore: 69 },
    { id: "m6", name: "BinWalker", avatar: "🤖", skills: ["Firmware Analysis", "IoT Security", "Assembly"], matchScore: 65 },
];

// ─── NOTIFICATIONS ───
export const mockNotifications = [
    { id: "n1", title: "Hackathon Starting Soon!", message: "CyberStrike Hackathon 2026 starts in 2 hours. Get ready!", timestamp: "2h ago", read: false, type: "event" },
    { id: "n2", title: "Workshop Tomorrow", message: "Intro to Penetration Testing begins tomorrow at 2:00 PM.", timestamp: "5h ago", read: false, type: "event" },
    { id: "n3", title: "New Badge Earned!", message: "Congratulations! You earned the 'CTF Champion' badge.", timestamp: "1d ago", read: true, type: "achievement" },
    { id: "n4", title: "Team Invite", message: "PhantomRoot invited you to join 'Packet Storms'.", timestamp: "2d ago", read: true, type: "team" },
    { id: "n5", title: "New Challenge Available", message: "A new Hard difficulty challenge has been added to the Arena.", timestamp: "3d ago", read: true, type: "challenge" },
];

// ─── CYBER MAP DATA ───
export const mockCyberAttacks = [
    { id: "a1", from: { lat: 55.75, lng: 37.62, city: "Moscow" }, to: { lat: 38.9, lng: -77.04, city: "Washington DC" }, type: "DDoS", severity: "Critical" },
    { id: "a2", from: { lat: 39.9, lng: 116.4, city: "Beijing" }, to: { lat: 35.68, lng: 139.69, city: "Tokyo" }, type: "Ransomware", severity: "High" },
    { id: "a3", from: { lat: 51.51, lng: -0.13, city: "London" }, to: { lat: 48.86, lng: 2.35, city: "Paris" }, type: "Phishing", severity: "Medium" },
    { id: "a4", from: { lat: 37.57, lng: 126.98, city: "Seoul" }, to: { lat: 1.35, lng: 103.82, city: "Singapore" }, type: "Malware", severity: "High" },
    { id: "a5", from: { lat: -23.55, lng: -46.63, city: "São Paulo" }, to: { lat: 40.71, lng: -74.01, city: "New York" }, type: "Data Breach", severity: "Critical" },
    { id: "a6", from: { lat: 28.61, lng: 77.21, city: "New Delhi" }, to: { lat: -33.87, lng: 151.21, city: "Sydney" }, type: "SQL Injection", severity: "Medium" },
    { id: "a7", from: { lat: 52.52, lng: 13.41, city: "Berlin" }, to: { lat: 59.93, lng: 30.32, city: "St. Petersburg" }, type: "Zero-Day Exploit", severity: "Critical" },
    { id: "a8", from: { lat: 34.05, lng: -118.24, city: "Los Angeles" }, to: { lat: 19.43, lng: -99.13, city: "Mexico City" }, type: "Brute Force", severity: "Low" },
];

// ─── DASHBOARD STATS ───
export const mockDashboardStats = {
    eventsJoined: 12,
    postsCreated: 45,
    leaderboardRank: 1,
    badgesEarned: 4,
    challengesCompleted: 3,
    reputation: 2540,
    weeklyActivity: [
        { day: "Mon", posts: 3, challenges: 1 },
        { day: "Tue", posts: 5, challenges: 2 },
        { day: "Wed", posts: 2, challenges: 0 },
        { day: "Thu", posts: 8, challenges: 3 },
        { day: "Fri", posts: 4, challenges: 1 },
        { day: "Sat", posts: 6, challenges: 2 },
        { day: "Sun", posts: 1, challenges: 0 },
    ],
    monthlyPoints: [
        { month: "Oct", points: 320 },
        { month: "Nov", points: 580 },
        { month: "Dec", points: 450 },
        { month: "Jan", points: 720 },
        { month: "Feb", points: 890 },
        { month: "Mar", points: 1100 },
    ],
};
