// ─── MOCK EVENTS ───
export const mockEvents = [
    {
        id: "ev1",
        title: "CyberStrike Hackathon 2026",
        type: "Hackathon",
        status: "Upcoming",
        date: "2026-03-15",
        time: "10:00 AM",
        location: "Virtual",
        description: "48-hour hackathon focused on building AI-powered cybersecurity tools. Build exploit detectors, threat analyzers, and more.",
        reward: 100,
        attendees: 128,
        maxAttendees: 200,
        tags: ["#AI", "#Hacking", "#BuildToBreak"],
        image: "🛡️",
    },
    {
        id: "ev2",
        title: "Intro to Penetration Testing",
        type: "Workshop",
        status: "Live",
        date: "2026-03-01",
        time: "2:00 PM",
        location: "Lab 404, CS Building",
        description: "Hands-on workshop covering Nmap, Burp Suite and OWASP Top 10 vulnerabilities with live demos.",
        reward: 50,
        attendees: 45,
        maxAttendees: 50,
        tags: ["#PenTest", "#OWASP"],
        image: "🔓",
    },
    {
        id: "ev3",
        title: "CTF: Binary Exploitation",
        type: "CTF",
        status: "Upcoming",
        date: "2026-03-22",
        time: "6:00 PM",
        location: "Virtual",
        description: "Capture the Flag challenge focusing on buffer overflows, ROP chains and shellcode writing.",
        reward: 100,
        attendees: 64,
        maxAttendees: 100,
        tags: ["#CTF", "#BinExp", "#Pwn"],
        image: "🏴",
    },
    {
        id: "ev4",
        title: "AI Ethics in Cybersecurity",
        type: "Conference",
        status: "Past",
        date: "2026-02-10",
        time: "9:00 AM",
        location: "Auditorium A",
        description: "Panel discussion with industry experts on responsible AI use in offensive and defensive security.",
        reward: 50,
        attendees: 200,
        maxAttendees: 200,
        tags: ["#AI", "#Ethics"],
        image: "🧠",
    },
    {
        id: "ev5",
        title: "Malware Reverse Engineering",
        type: "Workshop",
        status: "Past",
        date: "2026-02-20",
        time: "3:00 PM",
        location: "Cyber Lab B2",
        description: "Deep dive into static and dynamic analysis of real-world malware samples using Ghidra and x64dbg.",
        reward: 50,
        attendees: 35,
        maxAttendees: 40,
        tags: ["#Malware", "#ReverseEng"],
        image: "🦠",
    },
    {
        id: "ev6",
        title: "Zero-Day Summit 2026",
        type: "Conference",
        status: "Upcoming",
        date: "2026-04-05",
        time: "10:00 AM",
        location: "Convention Center",
        description: "Annual summit featuring keynotes from top security researchers, bug bounty hunters, and AI safety experts.",
        reward: 50,
        attendees: 340,
        maxAttendees: 500,
        tags: ["#ZeroDay", "#Conference"],
        image: "💀",
    },
];

// ─── MOCK LEADERBOARD ───
export const mockLeaderboard = [
    { id: 1, rank: 1, username: "NeoCypher", avatar: "👾", points: 2540, badges: ["CTF Champion", "AI Explorer", "Bug Hunter"], eventsAttended: 12, streak: 8 },
    { id: 2, rank: 2, username: "Sh4dowByte", avatar: "🕵️", points: 2210, badges: ["Hacker", "CTF Champion"], eventsAttended: 10, streak: 6 },
    { id: 3, rank: 3, username: "NullPtr_", avatar: "💀", points: 1980, badges: ["Bug Hunter", "AI Explorer"], eventsAttended: 9, streak: 5 },
    { id: 4, rank: 4, username: "PhantomRoot", avatar: "👻", points: 1750, badges: ["Hacker"], eventsAttended: 8, streak: 4 },
    { id: 5, rank: 5, username: "CryptoFox", avatar: "🦊", points: 1420, badges: ["AI Explorer", "Bug Hunter"], eventsAttended: 7, streak: 3 },
    { id: 6, rank: 6, username: "ByteStorm", avatar: "⚡", points: 1200, badges: ["CTF Champion"], eventsAttended: 6, streak: 2 },
    { id: 7, rank: 7, username: "V1rusQueen", avatar: "🦠", points: 1050, badges: ["Hacker", "Bug Hunter"], eventsAttended: 5, streak: 4 },
    { id: 8, rank: 8, username: "ZeroDayZen", avatar: "🧘", points: 890, badges: ["AI Explorer"], eventsAttended: 4, streak: 1 },
    { id: 9, rank: 9, username: "BinWalker", avatar: "🤖", points: 720, badges: ["Bug Hunter"], eventsAttended: 3, streak: 2 },
    { id: 10, rank: 10, username: "StackSmash", avatar: "💥", points: 580, badges: ["Hacker"], eventsAttended: 2, streak: 1 },
];

// ─── MOCK TEAMS ───
export const mockTeams = [
    {
        id: "t1",
        name: "Team Exploit",
        leader: "NeoCypher",
        members: ["NeoCypher", "Sh4dowByte", "NullPtr_"],
        maxMembers: 4,
        description: "Focused on binary exploitation and vulnerability research. Looking for a RE specialist.",
        tags: ["#Exploitation", "#RE"],
        status: "Recruiting",
        points: 4720,
    },
    {
        id: "t2",
        name: "Neural Breach",
        leader: "CryptoFox",
        members: ["CryptoFox", "ByteStorm", "V1rusQueen", "ZeroDayZen"],
        maxMembers: 4,
        description: "AI-powered security tools and adversarial ML research team.",
        tags: ["#AI", "#ML", "#Security"],
        status: "Full",
        points: 3560,
    },
    {
        id: "t3",
        name: "Packet Storms",
        leader: "PhantomRoot",
        members: ["PhantomRoot", "BinWalker"],
        maxMembers: 4,
        description: "Network security and wireless hacking enthusiasts. Join us for CTF domination!",
        tags: ["#Network", "#WiFi", "#CTF"],
        status: "Recruiting",
        points: 2470,
    },
    {
        id: "t4",
        name: "Cipher Squad",
        leader: "StackSmash",
        members: ["StackSmash"],
        maxMembers: 4,
        description: "Cryptography and blockchain security. New team looking for passionate members!",
        tags: ["#Crypto", "#Blockchain"],
        status: "Recruiting",
        points: 580,
    },
];

// ─── MOCK FEED ───
export const mockFeed = [
    {
        id: "p1",
        author: "NeoCypher",
        avatar: "👾",
        content: "Just found a fascinating paper on using transformers for automated vulnerability detection. The model achieves 94% accuracy on CWE classification. Link in comments! 🔥",
        tags: ["#AI", "#VulnDetection"],
        likes: 67,
        comments: 12,
        timestamp: "2h ago",
    },
    {
        id: "p2",
        author: "Sh4dowByte",
        avatar: "🕵️",
        content: "Writeup for last week's CTF binary challenge is live on my blog. Covered the full ROP chain construction from scratch. Hope it helps someone learning! 💻",
        tags: ["#CTF", "#Writeup", "#BinExp"],
        likes: 45,
        comments: 8,
        timestamp: "5h ago",
    },
    {
        id: "p3",
        author: "V1rusQueen",
        avatar: "🦠",
        content: "Anyone else notice the new obfuscation technique in the latest Emotet variant? The API hashing is completely different from previous samples. Thread below 🧵",
        tags: ["#Malware", "#ThreatIntel"],
        likes: 89,
        comments: 23,
        timestamp: "1d ago",
    },
    {
        id: "p4",
        author: "CryptoFox",
        avatar: "🦊",
        content: "Built a quick PoC for detecting prompt injection attacks in LLM-powered apps. It uses semantic similarity scoring to flag suspicious inputs. Repo link soon!",
        tags: ["#AI", "#LLMSecurity"],
        likes: 112,
        comments: 31,
        timestamp: "1d ago",
    },
    {
        id: "p5",
        author: "ZeroDayZen",
        avatar: "🧘",
        content: "Reminder: The CyberStrike Hackathon registration closes in 2 weeks! Our team still needs one more member. DM if you're into web exploitation or OSINT 🏴‍☠️",
        tags: ["#Hackathon", "#TeamRecruit"],
        likes: 34,
        comments: 6,
        timestamp: "2d ago",
    },
];

// ─── BADGES ───
export const badges = {
    "Hacker": { icon: "🏴‍☠️", color: "#00f7ff", description: "Participated in a hackathon" },
    "AI Explorer": { icon: "🧠", color: "#7a00ff", description: "Completed an AI workshop" },
    "Bug Hunter": { icon: "🐛", color: "#00ff9d", description: "Found and reported a bug" },
    "CTF Champion": { icon: "🏆", color: "#ffaa00", description: "Won a CTF competition" },
};

// ─── POINT SYSTEM ───
export const pointSystem = {
    hackathon: 100,
    workshop: 50,
    forumPost: 10,
    ctf: 100,
    conference: 50,
};

// ─── SENTINEL AI RESPONSES ───
export const sentinelResponses = {
    greetings: [
        "⚡ Greetings, operator. Sentinel AI online. How can I assist your cyber mission today?",
        "🛡️ Welcome back to the grid. What intel do you need?",
    ],
    events: [
        "📡 Scanning event database... We have the CyberStrike Hackathon coming up on March 15. It's a 48-hour AI security challenge. Want to register?",
        "🔔 Upcoming events: Hackathon (Mar 15), CTF Binary Exploitation (Mar 22), Zero-Day Summit (Apr 5). Which interests you?",
    ],
    resources: [
        "📚 Recommended resources:\n• TryHackMe – Beginner-friendly cyber labs\n• HackTheBox – Advanced pentesting\n• PortSwigger Academy – Web security\n• CryptoHack – Cryptography challenges",
        "🔗 Top picks: OWASP Testing Guide, MITRE ATT&CK Framework, and the OverTheWire wargames. Start with Bandit if you're new!",
    ],
    default: [
        "🤖 I'm still learning about that topic. Try asking about events, resources, or cybersecurity tips!",
        "⚙️ Command not recognized. Available queries: events, resources, tips, badges. What's your vector?",
    ],
    tips: [
        "🔐 Cyber tip: Always use unique passwords with a password manager. Enable 2FA everywhere. Trust no one, verify everything.",
        "💡 Pro tip: Practice on CTF platforms regularly. Consistency beats talent in cybersecurity.",
    ],
};

// ─── MOCK PROFILE ───
export const mockProfile = {
    username: "NeoCypher",
    avatar: "👾",
    bio: "Cybersecurity researcher & AI enthusiast. Breaking things to make them stronger. CTF addict.",
    skills: ["Python", "Reverse Engineering", "Machine Learning", "Network Security", "Web Exploitation"],
    github: "https://github.com/neocypher",
    linkedin: "https://linkedin.com/in/neocypher",
    eventsAttended: 12,
    points: 2540,
    badges: ["CTF Champion", "AI Explorer", "Bug Hunter"],
    rank: 1,
    joinDate: "Sept 2025",
    team: "Team Exploit",
};
